#!/bin/bash
# dotfiles_install
#
# Install a symlink to the needed dotfiles
# Copyright (C) 2013 De Meyer Maarten <de.meyer.maarten@gmail.com>
#

dotfiles_directory="$HOME/dotfiles"

if [ ! -e "$dotfiles_directory" ]; then
    printf 'Error: Dotfiles directory does not exist.'
    exit 1
fi

# File list
core="alias bashrc vimrc profile functions inputrc"
home="functions xinitrc Xresources"
dev="gitconfig kdesrc-buildrc kdesrc-f5-buildrc kf5 bash_kde commit-template"

# Select the files to install
package=${1:-base}
case $package in
    base)
        files="$core" ;;
    dev|kde)
        files="$core $dev" ;;
    home)
        files="$core $home" ;;
    *)
        echo "Package $package not found!" ;;
esac

# Backup dir
backupDir=~/.dotfiles_backup
mkdir -p $backupDir

cd $dotfiles_directory
for file in $files; do
    echo "Installing $file"
    if [ -f ~/.$file ]; then
        mv ~/.$file $backupDir
    fi

    if [ "$UID" -eq 0 ]; then
	# Don't use link for root!
	cp /home/maarten/src/dotfiles/$file ~/.$file
    else
    	ln -s "$dotfiles_directory/$file" "$HOME/.$file"
    fi
done

. ~/.bashrc

