#! /bin/bash
#
# Usefull functions
# Copyright (C) 2013 De Meyer Maarten <de.meyer.maarten@gmail.com>
#

# Create a build folder an build the source
function makebuild()
{
    base=`basename $PWD`
    if [ $base = "build" ] ; then
        cd ..
    fi

    shopt -s nullglob
    dirs=(*/)
    shopt -u nullglob

    for dir in "$dirs" ; do
        if [ $dir = "build/" ] ; then
            rm build/ -r
        fi
    done

    mkdir build
    cd build
    cmake ..

    echo "Press <ENTER> to continue..."
    read userinput
    make
}

# Rebuild source in current build folder
function build()
{
    base=`basename $PWD`
    if [ ! $base = "build" ] ; then
        # Wrong directory
        cd build/
    fi

    cmake ..
    make
}

# Extract archives
function extract()
{
    if [ -f $1 ] ; then
        ark --batch --autodestination --autosubfolder $1
   else
        echo "Not a valid file."
    fi
}

# Easy to use tar command
function maketar()
{  
    tar cvzf "$1%%/}.tar.gz"    "${1%%/}"
}

# Easy zip
function makezip()
{
    zip -r "${1%%/}.zip"    "$1"
}

